version: '3'
services:
  www:
    build: .
    privileged: true
    restart: always
    tty: true
    ports:
      - 8080:80
  db:
    image: mysql:5.5
    restart: always
    privileged: true
    tty: true
    ports:
      - 3334:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
